# Generated by Django 4.2.3 on 2023-09-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredient',
            field=models.ManyToManyField(related_name='recipes', to='recipe.recipeingredient'),
        ),
    ]
