# Generated by Django 4.2.3 on 2023-09-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipeingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredient',
            field=models.ManyToManyField(related_name='recipes_ingredient', to='recipe.recipeingredient'),
        ),
    ]
