# Generated by Django 4.2.3 on 2023-09-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='trivia_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
