# Generated by Django 4.2.3 on 2023-09-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0002_remove_recipeingredient_recipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipes', models.ManyToManyField(related_name='menus', to='recipe.recipe')),
            ],
        ),
    ]
